[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyALIVaf8gwwzKOkCfEUBlMxgeDBW8sUicU"
  VITE_FIREBASE_AUTH_DOMAIN = "tickzy-e986b.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "tickzy-e986b"
  VITE_FIREBASE_STORAGE_BUCKET = "tickzy-e986b.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "304409562549"
  VITE_FIREBASE_APP_ID = "1:304409562549:web:19b4c2d6210e12d56b9dfc"
